/**
 * Cases Service
 *
 * Unified facade for case management operations.
 * Delegates to focused modules for specific functionality.
 */

import type { NormalizedEntities } from "@odis-ai/shared/validators";
import type { SupabaseClientType } from "@odis-ai/shared/types/supabase";
import type {
  CaseScheduleOptions,
  IngestPayload,
  ScheduledDischargeCall,
} from "@odis-ai/shared/types/services";
import type { ICallExecutor } from "@odis-ai/domain/shared";

// Import from focused modules
import {
  createOrUpdateCase,
  getCaseWithEntities,
  deleteNoShowCase,
  type CreateOrUpdateCaseContext,
  type CaseWithEntities,
} from "./case-crud";
import {
  autoGenerateDischargeSummary,
  extractEntitiesFromIdexx,
  generateAndStoreCallIntelligence,
} from "./case-ai";
import { mapIdexxToEntities } from "./case-helpers";
import { scheduleDischargeCall } from "./call-scheduling";
import {
  isEntitiesIncomplete,
  getMissingEntityFields,
  enrichEntitiesWithPatient,
  getExtractedFields,
  mergeEntitiesForExtraction,
  mergeEntities,
} from "./entity-utils";

// Re-export types for convenience
export type { CaseScheduleOptions, IngestPayload, ScheduledDischargeCall };
export type { CreateOrUpdateCaseContext, CaseWithEntities };

/**
 * CasesService - Unified facade for case management
 */
export const CasesService = {
  /**
   * Main entry point for ingesting case data
   */
  async ingest(
    supabase: SupabaseClientType,
    userId: string,
    payload: IngestPayload,
  ): Promise<{
    caseId: string;
    entities: NormalizedEntities;
    scheduledCall: ScheduledDischargeCall | null;
  }> {
    let entities: NormalizedEntities | null = null;
    let rawIdexxData: Record<string, unknown> | null = null;
    let transcriptionText: string | null = null;

    // 1. Normalize Data
    if (payload.mode === "text") {
      transcriptionText = payload.text;
      // Run AI Normalization (dynamic import to avoid lazy-load constraint)
      const { extractEntitiesWithRetry } =
        await import("@odis-ai/integrations/ai/normalize-scribe");
      entities = await extractEntitiesWithRetry(
        payload.text,
        payload.options?.inputType,
      );
    } else {
      // Mode: structured (IDEXX)
      rawIdexxData = payload.data;

      // For IDEXX sources, try AI extraction from consultation notes first
      if (
        payload.source === "idexx_extension" ||
        payload.source === "idexx_neo"
      ) {
        const aiExtractedEntities =
          await extractEntitiesFromIdexx(rawIdexxData);

        if (aiExtractedEntities) {
          entities = aiExtractedEntities;
          console.log(
            "[CasesService] Used AI extraction from IDEXX consultation notes",
            {
              source: payload.source,
              patientName: entities.patient.name,
              confidence: entities.confidence?.overall,
            },
          );
        } else {
          // Fall back to basic mapping if AI extraction fails
          console.log(
            "[CasesService] Falling back to basic IDEXX field mapping",
            {
              source: payload.source,
            },
          );
          if (payload.data.patient && payload.data.clinical) {
            entities = payload.data as NormalizedEntities;
          } else {
            entities = mapIdexxToEntities(payload.data);
          }
        }
      } else {
        // Non-IDEXX structured data
        if (payload.data.patient && payload.data.clinical) {
          entities = payload.data as NormalizedEntities;
        } else {
          entities = mapIdexxToEntities(payload.data);
        }
      }
    }

    if (!entities) {
      throw new Error("Failed to extract entities from payload");
    }

    // 2. Find or Create Case (Smart Merge)
    const caseResult = await createOrUpdateCase(supabase, userId, entities, {
      rawIdexxData,
      transcriptionText,
      source: payload.source,
    });

    // 3. For IDEXX sources: Auto-generate discharge summary AND call intelligence
    if (
      payload.source === "idexx_extension" ||
      payload.source === "idexx_neo"
    ) {
      await autoGenerateDischargeSummary(
        supabase,
        userId,
        caseResult.caseId,
        caseResult.entities,
      );

      await generateAndStoreCallIntelligence(
        supabase,
        caseResult.caseId,
        caseResult.entities,
      );
    }

    // 4. Auto-Schedule if requested
    let scheduledCall = null;
    if (payload.options?.autoSchedule) {
      const scheduledAt = new Date();

      scheduledCall = await scheduleDischargeCall(
        supabase,
        userId,
        caseResult.caseId,
        {
          scheduledAt,
        },
      );
    }

    return {
      caseId: caseResult.caseId,
      entities: caseResult.entities,
      scheduledCall,
    };
  },

  // Delegate to focused modules
  createOrUpdateCase,
  getCaseWithEntities,
  deleteNoShowCase,
  autoGenerateDischargeSummary,
  extractEntitiesFromIdexx,
  generateAndStoreCallIntelligence,
  scheduleDischargeCall: (
    supabase: SupabaseClientType,
    userId: string,
    caseId: string,
    options: CaseScheduleOptions,
    callExecutor?: ICallExecutor,
  ) => scheduleDischargeCall(supabase, userId, caseId, options, callExecutor),

  // Entity utility methods
  isEntitiesIncomplete,
  getMissingEntityFields,
  enrichEntitiesWithPatient,
  getExtractedFields,
  mergeEntitiesForExtraction,
  mergeEntities,
};
