import type { Metadata } from "next";
import { Outfit, Inter, Lora, Plus_Jakarta_Sans } from "next/font/google";
import { GeistMono } from "geist/font/mono";
import { Analytics } from "@vercel/analytics/next";
import Script from "next/script";
import "~/styles/globals.css";
import { ClerkProvider } from "~/components/providers/clerk-provider";
import { ClientProviders } from "~/components/providers/client-providers";
import { StructuredData } from "~/components/seo/structured-data";
import { env } from "~/env.js";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
  display: "swap",
});

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta",
  display: "swap",
});

const geistMono = GeistMono;

const siteUrl = env.NEXT_PUBLIC_SITE_URL;

export const metadata: Metadata = {
  title: {
    default: "OdisAI - AI Voice Agents for Veterinary Clinics",
    template: "%s | OdisAI",
  },
  description:
    "Never miss another call. OdisAI handles your clinic's inbound and outbound calls with AI voice agents that sound natural, book appointments, and follow up with pet parents 24/7.",
  keywords: [
    // Core product keywords (high intent)
    "veterinary AI",
    "AI voice agents",
    "veterinary AI voice agent",
    "AI phone answering for vets",
    "veterinary virtual receptionist",
    "automated veterinary phone system",
    "AI receptionist for animal hospitals",

    // Integration keywords (competitor capture)
    "IDEXX Neo integration",
    "ezyVet phone integration",
    "veterinary PIMS integration",

    // Problem-solution keywords
    "veterinary phone answering",
    "vet clinic automation",
    "missed calls veterinary practice",
    "after hours vet phone service",
    "24/7 veterinary answering service",
    "24/7 veterinary phone service",

    // Discharge/follow-up keywords (unique value prop)
    "pet parent follow-up",
    "automated discharge calls veterinary",
    "pet discharge follow-up calls",
    "veterinary patient follow-up automation",

    // Use case keywords
    "veterinary appointment booking",
    "veterinary appointment scheduling AI",
    "AI receptionist",
    "emergency vet call routing",
    "vet clinic call overflow handling",

    // Long-tail keywords
    "veterinary practice management",
    "animal hospital software",
    "AI that books vet appointments",
    "best phone system for vet clinics",
    "veterinary answering service alternative",
  ],
  authors: [{ name: "OdisAI" }],
  creator: "OdisAI",
  publisher: "OdisAI",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  metadataBase: new URL(siteUrl),
  openGraph: {
    type: "website",
    locale: "en_US",
    url: siteUrl,
    title: "OdisAI - AI Voice Agents for Veterinary Clinics",
    description:
      "Never miss another call. OdisAI handles your clinic's inbound and outbound calls with AI voice agents that sound natural, book appointments, and follow up with pet parents 24/7.",
    siteName: "OdisAI",
    // Note: OG image is auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "OdisAI - AI Voice Agents for Veterinary Clinics",
    description:
      "Never miss another call. OdisAI handles your clinic's inbound and outbound calls with AI voice agents that sound natural, book appointments, and follow up with pet parents 24/7.",
    creator: "@odisai",
    // Note: Twitter image is auto-generated by opengraph-image.tsx
  },
  alternates: {
    canonical: siteUrl,
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  verification: {
    google: process.env.GOOGLE_SITE_VERIFICATION,
  },
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/icon-128.png", sizes: "128x128", type: "image/png" },
    ],
    apple: "/icon-128.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="light bg-[hsl(185,25%,7%)]">
      <head>
        <link rel="dns-prefetch" href="https://www.googletagmanager.com" />
        <link rel="dns-prefetch" href="https://us.i.posthog.com" />
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=AW-17852929075"
          strategy="lazyOnload"
        />
        <Script id="google-ads" strategy="lazyOnload">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'AW-17852929075');
          `}
        </Script>
      </head>
      <body
        className={`font-sans antialiased ${outfit.variable} ${inter.variable} ${lora.variable} ${plusJakarta.variable} ${geistMono.variable}`}
      >
        <ClerkProvider>
          <StructuredData />
          <ClientProviders>{children}</ClientProviders>
          <Analytics />
        </ClerkProvider>
      </body>
    </html>
  );
}
