/**
 * Post-Surgical Condition Knowledge Base
 *
 * Comprehensive knowledge base for post-operative care including spay/neuter,
 * mass removals, dental surgeries, orthopedic procedures, and other surgical interventions.
 */

import type { ConditionKnowledgeBase } from "../types";

export const postSurgicalKnowledge: ConditionKnowledgeBase = {
  conditionCategory: "post-surgical",
  displayName: "Post-Surgical Care",
  description:
    "Recovery monitoring for any surgical procedure including spay/neuter, mass removals, dental surgeries, and orthopedic procedures",

  keywords: [
    "surgery",
    "surgical",
    "spay",
    "neuter",
    "incision",
    "stitches",
    "sutures",
    "castration",
    "ovariohysterectomy",
    "post-op",
    "post-operative",
    "procedure",
    "mass removal",
    "tumor removal",
    "dental surgery",
    "orthopedic surgery",
    "amputation",
  ],

  assessmentQuestions: [
    {
      question: `How's the incision site looking? Is there any redness, swelling, or discharge?`,
      context: "Primary concern is infection and dehiscence at surgical site",
      expectedPositiveResponse: [
        "looks good",
        "healing well",
        "clean",
        "dry",
        "slight redness but improving",
        "minimal swelling",
        "normal",
        "healthy looking",
      ],
      concerningResponses: [
        "very red",
        "swollen",
        "oozing",
        "yellow discharge",
        "green discharge",
        "pus",
        "smells bad",
        "opening up",
        "coming apart",
        "gaping",
        "separated",
      ],
      followUpIfConcerning: `Is there any discharge coming from the incision? What color is it? And are the stitches still intact or has the incision opened?`,
      priority: 1,
      required: true,
    },
    {
      question: `Is {{petName}} leaving the incision alone, or trying to lick or chew at it?`,
      context: "Licking can cause infection, dehiscence, and delayed healing",
      expectedPositiveResponse: [
        "leaving it alone",
        "e-collar working well",
        "cone working",
        "not interested in it",
        "ignoring it",
        "not licking",
      ],
      concerningResponses: [
        "constantly licking",
        "chewing at it",
        "removed e-collar",
        "got around e-collar",
        "opened stitches",
        "obsessed with it",
        "keeps trying",
      ],
      followUpIfConcerning: `Has {{petName}} been able to lick the incision at all? Are the stitches still intact?`,
      priority: 1,
      required: true,
    },
    {
      question: `How's {{petName}}'s pain level? Does {{petName}} seem comfortable or still sore?`,
      context: "Pain assessment for adequate post-operative pain management",
      expectedPositiveResponse: [
        "seems comfortable",
        "sleeping well",
        "moving around okay",
        "pain seems controlled",
        "resting comfortably",
        "calm",
        "relaxed",
      ],
      concerningResponses: [
        "crying",
        "whimpering",
        "can't get comfortable",
        "panting heavily",
        "won't move",
        "screaming when touched",
        "very restless",
        "seems painful",
      ],
      followUpIfConcerning: `Is {{petName}} crying or whimpering constantly? And is {{petName}} panting heavily even when resting?`,
      priority: 1,
      required: true,
    },
    {
      question: `How's {{petName}}'s appetite? Is {{petName}} eating normally?`,
      context: "Appetite indicates pain control and absence of complications",
      expectedPositiveResponse: [
        "eating well",
        "back to normal",
        "good appetite",
        "eating everything",
        "hungry",
        "finishing meals",
      ],
      concerningResponses: [
        "not eating at all",
        "refusing food",
        "only tiny amounts",
        "no interest",
        "turning away",
      ],
      followUpIfConcerning: `Is {{petName}} drinking water at least? And for how long has {{petName}} refused food completely?`,
      priority: 2,
      required: true,
    },
    {
      question: `How's {{petName}}'s activity level? Is {{petName}} resting or trying to run and jump?`,
      context: "Activity restriction is critical for proper healing",
      expectedPositiveResponse: [
        "resting quietly",
        "calm",
        "taking it easy",
        "sleeping a lot",
        "relaxed",
        "not very active",
      ],
      concerningResponses: [
        "running around",
        "jumping",
        "very active",
        "can't keep calm",
        "bouncing off walls",
        "playing hard",
      ],
      followUpIfConcerning: `Is {{petName}} jumping on and off furniture? We really need to limit activity for proper healing.`,
      priority: 3,
      required: false,
    },
    {
      question: `Has {{petName}} had any vomiting or diarrhea since the surgery?`,
      context: "GI upset can occur from anesthesia or pain medications",
      expectedPositiveResponse: [
        "no vomiting",
        "no diarrhea",
        "normal bowel movements",
        "eating and drinking normally",
      ],
      concerningResponses: [
        "vomiting",
        "threw up",
        "diarrhea",
        "not keeping food down",
        "bloody stool",
      ],
      followUpIfConcerning: `How many times has {{petName}} vomited? And is {{petName}} able to keep water down?`,
      priority: 2,
      required: false,
    },
    {
      question: `Is {{petName}} urinating and defecating normally?`,
      context:
        "Monitoring elimination - especially important for certain surgeries",
      expectedPositiveResponse: [
        "yes",
        "normal",
        "going regularly",
        "no problems",
        "urinating fine",
        "normal bowel movements",
      ],
      concerningResponses: [
        "not urinating",
        "straining",
        "hasn't urinated",
        "hasn't pooped",
        "blood in urine",
        "crying when urinating",
      ],
      followUpIfConcerning: `When was the last time {{petName}} urinated? And is there any straining or blood?`,
      priority: 2,
      required: false,
    },
    {
      question: `Are you keeping the e-collar on {{petName}} full-time, or taking it off periodically?`,
      context: "E-collar compliance is critical for incision protection",
      expectedPositiveResponse: [
        "on full-time",
        "always on",
        "only off during supervised meals",
        "following instructions",
      ],
      concerningResponses: [
        "taking it off",
        "not using it",
        "off most of the time",
        "only on sometimes",
        "won't keep it on",
      ],
      followUpIfConcerning: `It's really important to keep the e-collar on at all times except during supervised feeding. Has {{petName}} been able to reach the incision?`,
      priority: 3,
      required: false,
    },
  ],

  normalPostTreatmentExpectations: [
    `Some swelling and redness at the incision is normal for the first 24-48 hours`,
    `Mild lethargy for 24-48 hours after surgery is expected from anesthesia`,
    `Decreased appetite for 12-24 hours post-surgery is common`,
    `Some bruising may develop around the incision site (especially with abdominal surgery)`,
    `Mild discomfort or stiffness for the first few days is normal`,
    `Small amount of clear or slightly pink discharge from incision in first 24 hours can be normal`,
    `Dogs may seem quieter or less interested in play for several days`,
  ],

  warningSignsToMonitor: [
    `Incision becoming increasingly red, swollen, or warm to the touch`,
    `Any discharge from the incision (yellow, green, or bloody)`,
    `Incision opening or stitches coming apart`,
    `Excessive licking despite e-collar (incision protection failure)`,
    `Persistent vomiting (more than 1-2 times)`,
    `Not eating or drinking for more than 24 hours`,
    `Severe lethargy (won't get up, non-responsive)`,
    `Signs of severe pain (crying, aggressive when touched, won't settle)`,
    `No urination for more than 24 hours`,
    `Difficulty breathing or increased respiratory rate at rest`,
  ],

  emergencyCriteria: [
    `Incision completely opening (dehiscence) with visible internal tissues`,
    `Large amount of bleeding from incision site`,
    `Collapse or inability to stand`,
    `Difficulty breathing, pale or blue gums`,
    `Seizures`,
    `Extreme abdominal distension (especially after abdominal surgery)`,
    `Persistent screaming or crying in pain`,
    `Uncontrolled vomiting or bloody vomit`,
    `Cold extremities or very pale gums (shock signs)`,
  ],

  urgentCriteria: [
    `Incision with yellow or green discharge (infection)`,
    `Incision beginning to open or gaps between stitches`,
    `Persistent licking resulting in very red, irritated incision`,
    `Not eating or drinking for 24+ hours`,
    `Vomiting more than 2-3 times`,
    `Severe lethargy (major change from normal)`,
    `Signs of significant pain despite medication`,
    `Straining to urinate or defecate with no production`,
    `Bruising that's spreading rapidly`,
  ],

  typicalRecoveryDays: 10,

  commonMedications: [
    "carprofen",
    "rimadyl",
    "meloxicam",
    "gabapentin",
    "trazodone",
    "tramadol",
    "onsior",
    "galliprant",
    "cephalexin",
    "amoxicillin",
    "clavamox",
  ],
};
