/**
 * Tests for services-cases/CasesService
 *
 * Tests the CasesService exported interface and basic behavior.
 * Full integration tests require extensive mocking of AI, QStash, and Supabase.
 */

import { describe, it, expect, vi, beforeEach } from "vitest";
import { CasesService } from "../lib/cases-service";

// Mock all external dependencies
vi.mock("@odis-ai/integrations/ai/normalize-scribe", () => ({
  extractEntitiesWithRetry: vi.fn(),
}));

vi.mock("@odis-ai/integrations/ai/generate-structured-discharge", () => ({
  generateStructuredDischargeSummaryWithRetry: vi.fn(),
}));

vi.mock("@odis-ai/integrations/ai/generate-assessment-questions", () => ({
  generateCallIntelligenceFromEntities: vi.fn(),
}));

vi.mock("@odis-ai/qstash/client", () => ({
  scheduleCallExecution: vi.fn(),
}));

vi.mock("@odis-ai/integrations/vapi/knowledge-base", () => ({
  buildDynamicVariables: vi.fn(),
}));

vi.mock("@odis-ai/integrations/vapi/extract-variables", () => ({
  extractVapiVariablesFromEntities: vi.fn(),
}));

vi.mock("@odis-ai/clinics/vapi-config", () => ({
  getClinicVapiConfigByUserId: vi.fn(),
}));

describe("CasesService", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe("exported interface", () => {
    it("exports CasesService object", () => {
      expect(CasesService).toBeDefined();
      expect(typeof CasesService).toBe("object");
    });

    it("has ingest method", () => {
      expect(CasesService.ingest).toBeDefined();
      expect(typeof CasesService.ingest).toBe("function");
    });

    it("has createOrUpdateCase method", () => {
      expect(CasesService.createOrUpdateCase).toBeDefined();
      expect(typeof CasesService.createOrUpdateCase).toBe("function");
    });

    it("has getCaseWithEntities method", () => {
      expect(CasesService.getCaseWithEntities).toBeDefined();
      expect(typeof CasesService.getCaseWithEntities).toBe("function");
    });

    it("has autoGenerateDischargeSummary method", () => {
      expect(CasesService.autoGenerateDischargeSummary).toBeDefined();
      expect(typeof CasesService.autoGenerateDischargeSummary).toBe("function");
    });

    it("has extractEntitiesFromIdexx method", () => {
      expect(CasesService.extractEntitiesFromIdexx).toBeDefined();
      expect(typeof CasesService.extractEntitiesFromIdexx).toBe("function");
    });

    it("has generateAndStoreCallIntelligence method", () => {
      expect(CasesService.generateAndStoreCallIntelligence).toBeDefined();
      expect(typeof CasesService.generateAndStoreCallIntelligence).toBe(
        "function",
      );
    });

    it("has scheduleDischargeCall method", () => {
      expect(CasesService.scheduleDischargeCall).toBeDefined();
      expect(typeof CasesService.scheduleDischargeCall).toBe("function");
    });
  });

  describe("ingest validation", () => {
    it("throws when entities cannot be extracted", async () => {
      const mockSupabase = {} as any;
      const { extractEntitiesWithRetry } =
        await import("@odis-ai/integrations/ai/normalize-scribe");

      // Mock to return null (no entities extracted)
      vi.mocked(extractEntitiesWithRetry).mockResolvedValue(
        null as unknown as any,
      );

      await expect(
        CasesService.ingest(mockSupabase, "user-123", {
          mode: "text",
          text: "Some veterinary text",
          source: "scribe",
        }),
      ).rejects.toThrow("Failed to extract entities from payload");
    });
  });

  describe("getCaseWithEntities", () => {
    it("returns null when case not found", async () => {
      const mockSupabase = {
        from: vi.fn().mockReturnThis(),
        select: vi.fn().mockReturnThis(),
        eq: vi.fn().mockReturnThis(),
        single: vi.fn().mockResolvedValue({ data: null, error: null }),
      } as any;

      const result = await CasesService.getCaseWithEntities(
        mockSupabase,
        "user-123",
        "non-existent-case",
      );

      expect(result).toBeNull();
    });

    it("returns null when supabase returns error", async () => {
      const mockSupabase = {
        from: vi.fn().mockReturnThis(),
        select: vi.fn().mockReturnThis(),
        eq: vi.fn().mockReturnThis(),
        single: vi.fn().mockResolvedValue({
          data: null,
          error: { message: "Database error" },
        }),
      } as any;

      const result = await CasesService.getCaseWithEntities(
        mockSupabase,
        "user-123",
        "case-456",
      );

      expect(result).toBeNull();
    });
  });

  describe("extractEntitiesFromIdexx", () => {
    it("returns null when no consultation notes", async () => {
      const result = await CasesService.extractEntitiesFromIdexx({});

      expect(result).toBeNull();
    });

    it("returns null when consultation notes are empty", async () => {
      const result = await CasesService.extractEntitiesFromIdexx({
        consultation_notes: "",
      });

      expect(result).toBeNull();
    });

    it("returns null when consultation notes are too short", async () => {
      const result = await CasesService.extractEntitiesFromIdexx({
        consultation_notes: "Short text",
      });

      expect(result).toBeNull();
    });
  });
});
