import { execSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const workspaceRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const referenceDir = path.join(workspaceRoot, "docs", "reference");

mkdirSync(referenceDir, { recursive: true });

function runJSON(command) {
  const output = execSync(command, {
    cwd: workspaceRoot,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "inherit"],
  });
  return JSON.parse(output);
}

function getTagValue(tags, prefix, fallback) {
  const match = tags?.find((tag) => tag.startsWith(prefix));
  return match ? match.replace(prefix, "") : fallback;
}

const projectNames = runJSON("pnpm nx show projects --json");
const projects = projectNames.map((name) => {
  const data = runJSON(`pnpm nx show project ${name} --json`);
  return { name, ...data };
});

const projectRows = projects
  .map((project) => {
    const tags = project.tags ?? [];
    const type = getTagValue(tags, "type:", project.projectType ?? "unknown");
    const scope = getTagValue(tags, "scope:", "shared");
    const platform = getTagValue(tags, "platform:", "neutral");
    const targets = Object.keys(project.targets ?? {}).sort();

    return {
      name: project.name,
      type,
      scope,
      platform,
      sourceRoot: project.sourceRoot ?? project.root ?? "",
      targets,
    };
  })
  .sort((a, b) => a.name.localeCompare(b.name));

const markdownLines = [
  "# Nx Project Inventory",
  "",
  `Generated: ${new Date().toISOString()}`,
  "Source: `pnpm docs:nx` (scripts/generate-nx-docs.js)",
  "",
  "| Project | Type | Scope | Platform | Targets | Source |",
  "| --- | --- | --- | --- | --- | --- |",
  ...projectRows.map(
    (row) =>
      `| ${row.name} | ${row.type} | ${row.scope} | ${row.platform} | ${row.targets.join(
        ", ",
      )} | ${row.sourceRoot} |`,
  ),
  "",
  "Do not edit this file manually. Regenerate with `pnpm docs:nx`.",
];

writeFileSync(
  path.join(referenceDir, "NX_PROJECTS.md"),
  markdownLines.join("\n"),
  "utf8",
);

writeFileSync(
  path.join(referenceDir, "nx-projects.json"),
  JSON.stringify(projectRows, null, 2),
  "utf8",
);
