/**
 * Gastrointestinal Condition Knowledge Base
 *
 * Comprehensive knowledge base for GI-related conditions including vomiting, diarrhea,
 * gastroenteritis, pancreatitis, dietary indiscretion, and other digestive issues.
 */

import type { ConditionKnowledgeBase } from '../types';

export const gastrointestinalKnowledge: ConditionKnowledgeBase = {
  conditionCategory: 'gastrointestinal',
  displayName: 'Gastrointestinal Issues',
  description:
    'Conditions affecting the digestive system including vomiting, diarrhea, gastroenteritis, pancreatitis, and dietary indiscretion',

  keywords: [
    'vomit',
    'vomiting',
    'diarrhea',
    'gastroenteritis',
    'pancreatitis',
    'gi',
    'gastrointestinal',
    'stomach',
    'intestinal',
    'nausea',
    'gastro',
    'colitis',
    'enteritis',
    'bowel',
    'digestive',
    'dietary indiscretion',
    'ate something',
  ],

  assessmentQuestions: [
    {
      question: `Has the vomiting decreased since starting the medication?`,
      context: 'Primary indicator of treatment effectiveness for GI issues',
      expectedPositiveResponse: [
        'stopped completely',
        'much less frequent',
        'only once or twice',
        'almost stopped',
        'barely any',
        'way better',
        'significantly reduced',
        'not vomiting anymore',
      ],
      concerningResponses: [
        'still vomiting frequently',
        'vomiting blood',
        'bloody vomit',
        'projectile vomiting',
        'worse than before',
        'same as before',
        'every few hours',
        'uncontrolled',
        'coffee ground',
      ],
      followUpIfConcerning: `How many times has {{petName}} vomited in the last 24 hours? And is there any blood or dark material in the vomit?`,
      priority: 1,
      required: true,
    },
    {
      question: `How's {{petName}}'s appetite been? Is {{petName}} eating normally?`,
      context: 'Appetite is a key indicator of GI recovery and hydration status',
      expectedPositiveResponse: [
        'eating well',
        'back to normal',
        'hungry',
        'finishing meals',
        'good appetite',
        'eating everything',
        'begging for food',
        'acting hungry',
      ],
      concerningResponses: [
        'not eating at all',
        'refusing food',
        'only eating tiny amounts',
        "won't eat for 24 hours",
        'no interest',
        'turning away from food',
        'completely stopped eating',
      ],
      followUpIfConcerning: `Is {{petName}} drinking water at least? And has {{petName}} completely refused food for more than 12 hours?`,
      priority: 1,
      required: true,
    },
    {
      question: `What about the diarrhea - has that improved?`,
      context: 'Stool consistency indicates GI tract healing and function',
      expectedPositiveResponse: [
        'much better',
        'almost normal',
        'firmer',
        'less frequent',
        'formed stool',
        'normal now',
        'solid',
        'way better',
        'back to normal',
      ],
      concerningResponses: [
        'bloody diarrhea',
        'bright red blood',
        'black tarry stool',
        'melena',
        'watery',
        'not improved at all',
        'worse',
        'explosive',
        'mucus',
        'constant',
      ],
      followUpIfConcerning: `Is there any blood in the stool - either bright red or very dark and black? And how many times has {{petName}} had diarrhea in the last 24 hours?`,
      priority: 1,
      required: true,
    },
    {
      question: `How's {{petName}}'s energy level compared to when you brought {{petName}} in?`,
      context: 'Energy level correlates with hydration status and overall recovery',
      expectedPositiveResponse: [
        'more energetic',
        'playing again',
        'back to normal',
        'much perkier',
        'active',
        'running around',
        'back to usual self',
        'lively',
      ],
      concerningResponses: [
        'very lethargic',
        "won't get up",
        'weak',
        'collapsed',
        'not moving much',
        'just sleeping',
        'no energy',
        'worse',
      ],
      followUpIfConcerning: `Is {{petName}} able to walk around on {{petName}}'s own, or is {{petName}} too weak to stand?`,
      priority: 2,
      required: true,
    },
    {
      question: `Is {{petName}} keeping the medication down, or is {{petName}} vomiting it back up?`,
      context: 'Critical to know if treatment is being absorbed',
      expectedPositiveResponse: [
        'keeping it down',
        'no problem',
        'taking it well',
        'not vomiting after',
        'tolerating it',
      ],
      concerningResponses: [
        'vomiting it back up',
        'throwing it up',
        'comes right back up',
        "can't keep it down",
        'vomits after taking it',
      ],
      followUpIfConcerning: `How soon after giving the medication does {{petName}} vomit it back up?`,
      priority: 2,
      required: false,
    },
    {
      question: `Are you noticing any changes in {{petName}}'s water intake?`,
      context: 'Hydration status is critical for GI recovery',
      expectedPositiveResponse: [
        'drinking normally',
        'drinking well',
        'good water intake',
        'drinking plenty',
      ],
      concerningResponses: [
        'not drinking',
        'excessive thirst',
        'drinking constantly',
        "won't touch water",
        'refusing water',
      ],
      followUpIfConcerning: `Has {{petName}} refused water for more than 6-8 hours?`,
      priority: 3,
      required: false,
    },
    {
      question: `Have you noticed any abdominal discomfort - like hunching, whining when touched, or restlessness?`,
      context: 'Abdominal pain assessment',
      expectedPositiveResponse: [
        'no pain',
        'comfortable',
        'not sensitive',
        'no hunching',
        'relaxed',
      ],
      concerningResponses: [
        'very painful',
        'whining',
        'crying when touched',
        'hunched posture',
        'prayer position',
        'tense abdomen',
        'swollen belly',
        'hard stomach',
      ],
      followUpIfConcerning: `Is {{petName}}'s abdomen visibly swollen or hard to the touch? And is {{petName}} in a "prayer position" with front down and rear up?`,
      priority: 2,
      required: false,
    },
  ],

  normalPostTreatmentExpectations: [
    `Gradual improvement over 24-48 hours is normal - not all symptoms resolve immediately`,
    `Some pets may be tired from dehydration initially, even as they improve`,
    `Appetite may take 1-2 days to fully return after severe vomiting`,
    `Stools may be softer than normal for a few days even with improvement`,
    `Mild abdominal sensitivity may persist for 24 hours as the GI tract heals`,
    `Some pets may have decreased energy for 24-48 hours while recovering`,
    `Occasional soft stool or single vomiting episode during recovery can be normal`,
  ],

  warningSignsToMonitor: [
    `Vomiting more than 2-3 times in 24 hours despite medication`,
    `Any blood in vomit (bright red or coffee-ground appearance)`,
    `Blood in stool (bright red) or black, tarry stools (melena)`,
    `Refusing water for more than 12 hours`,
    `Progressively more lethargic or weak`,
    `Painful, distended, or hard abdomen`,
    `Gums that are pale, white, or tacky/dry (dehydration sign)`,
    `No improvement after 48 hours of treatment`,
    `Hunched posture or "prayer position" (front down, rear up)`,
    `Restlessness, pacing, or inability to get comfortable`,
  ],

  emergencyCriteria: [
    `Vomiting bright red blood or large amounts of coffee-ground material`,
    `Large amounts of bright red blood in stool`,
    `Collapse or inability to stand`,
    `Severe abdominal distension with distress (concern for bloat/GDV)`,
    `Uncontrolled diarrhea with signs of severe dehydration (sunken eyes, extreme lethargy)`,
    `Seizures`,
    `Gums that are white, blue, or very pale`,
    `Difficulty breathing or open-mouth breathing`,
    `Sudden severe abdominal pain with rigid abdomen`,
  ],

  urgentCriteria: [
    `Persistent vomiting (more than 3 times) in 24 hours despite medication`,
    `No improvement after 48 hours of treatment`,
    `Not eating or drinking for 24+ hours`,
    `Significant lethargy (won't get up, barely responsive)`,
    `Small amounts of blood in stool or vomit`,
    `Medication not being tolerated (vomiting it back up repeatedly)`,
    `Signs of abdominal pain (whining, hunching, sensitivity to touch)`,
    `Diarrhea more than 6-8 times in 24 hours`,
    `Dry, tacky gums indicating dehydration`,
  ],

  typicalRecoveryDays: 2,

  commonMedications: [
    'metronidazole',
    'cerenia',
    'maropitant',
    'famotidine',
    'omeprazole',
    'sucralfate',
    'probiotics',
    'fortiflora',
    'bland diet',
    'i/d diet',
    'metoclopramide',
  ],
};
