/**
 * Neurological Condition Knowledge Base
 *
 * Comprehensive knowledge base for neurological conditions including seizures,
 * vestibular disease, IVDD, paralysis, and other nervous system disorders.
 */

import type { ConditionKnowledgeBase } from '../types';

export const neurologicalKnowledge: ConditionKnowledgeBase = {
  conditionCategory: 'neurological',
  displayName: 'Neurological Issues',
  description:
    'Conditions affecting the nervous system including seizures, vestibular disease, intervertebral disc disease, paralysis, and tremors',

  keywords: [
    'seizure',
    'seizures',
    'convulsion',
    'neurological',
    'neuro',
    'paralysis',
    'paralyzed',
    'tremor',
    'shaking',
    'ataxia',
    'wobbly',
    'disc',
    'ivdd',
    'intervertebral',
    'vestibular',
    'head tilt',
    'circling',
    'weakness',
    'dragging',
  ],

  assessmentQuestions: [
    {
      question: `Has {{petName}} had any more seizures since starting the medication?`,
      context: 'Primary concern for seizure disorders',
      expectedPositiveResponse: [
        'no more seizures',
        'seizure-free',
        'no seizures',
        'controlled',
      ],
      concerningResponses: [
        'had another seizure',
        'multiple seizures',
        'cluster seizures',
        'worse',
        'longer seizures',
      ],
      followUpIfConcerning: `How many seizures has {{petName}} had since starting medication? And how long did they last? If there were more than two seizures in 24 hours, this is an emergency.`,
      priority: 1,
      required: true,
    },
    {
      question: `How's {{petName}}'s balance and coordination? Can {{petName}} walk normally?`,
      context: 'Neurological function assessment',
      expectedPositiveResponse: [
        'walking normally',
        'balance improved',
        'coordinated',
        'back to normal',
        'steady',
      ],
      concerningResponses: [
        'still wobbly',
        'falling over',
        'can\'t walk',
        'dragging legs',
        'worse',
        'circling',
      ],
      followUpIfConcerning: `Is {{petName}} able to stand on their own, or do they need support? And are the rear legs or front legs affected?`,
      priority: 1,
      required: true,
    },
    {
      question: `Is {{petName}} able to urinate and defecate on their own?`,
      context: 'Critical for spinal cord function assessment',
      expectedPositiveResponse: [
        'yes',
        'going normally',
        'no problems',
        'control is good',
      ],
      concerningResponses: [
        'no',
        'can\'t urinate',
        'leaking urine',
        'no control',
        'can\'t defecate',
      ],
      followUpIfConcerning: `This is very important - has {{petName}} urinated or had a bowel movement in the last 12 hours? Loss of bladder or bowel control suggests serious spinal involvement.`,
      priority: 1,
      required: true,
    },
    {
      question: `Are you noticing any improvement in {{petName}}'s symptoms, or are they about the same?`,
      context: 'General neurological progress assessment',
      expectedPositiveResponse: [
        'improving',
        'better',
        'getting stronger',
        'more alert',
        'recovering',
      ],
      concerningResponses: [
        'worse',
        'no improvement',
        'declining',
        'weaker',
        'less responsive',
      ],
      followUpIfConcerning: `Can you describe what's getting worse? Is it the wobbliness, weakness, or something else?`,
      priority: 2,
      required: true,
    },
    {
      question: `Is {{petName}} eating and drinking normally?`,
      context: 'Ability to eat/drink indicates brain function',
      expectedPositiveResponse: [
        'yes',
        'eating well',
        'drinking normally',
        'good appetite',
      ],
      concerningResponses: [
        'not eating',
        'can\'t swallow',
        'choking',
        'not drinking',
        'difficulty eating',
      ],
      followUpIfConcerning: `Is {{petName}} able to swallow food and water, or is {{petName}} gagging or choking when trying to eat?`,
      priority: 2,
      required: false,
    },
    {
      question: `How's {{petName}}'s mental state? Is {{petName}} alert and recognizing you?`,
      context: 'Cognitive function assessment',
      expectedPositiveResponse: [
        'alert',
        'recognizes us',
        'responsive',
        'normal',
        'bright',
      ],
      concerningResponses: [
        'dull',
        'not responsive',
        'staring',
        'confused',
        'doesn\'t recognize us',
        'lethargic',
      ],
      followUpIfConcerning: `Does {{petName}} respond when you call {{petName}}'s name? And do {{petName}}'s eyes track you when you move?`,
      priority: 2,
      required: false,
    },
    {
      question: `If {{petName}} has a head tilt, is it getting better, worse, or staying the same?`,
      context: 'Vestibular disease progress',
      expectedPositiveResponse: [
        'improving',
        'less tilted',
        'almost gone',
        'better',
      ],
      concerningResponses: [
        'worse',
        'more severe',
        'can\'t hold head up',
        'rolling',
      ],
      followUpIfConcerning: `Is {{petName}} rolling or unable to stand because of the head tilt?`,
      priority: 2,
      required: false,
    },
  ],

  normalPostTreatmentExpectations: [
    `Vestibular disease may take 7-14 days to show improvement`,
    `Some head tilt may persist even after recovery`,
    `Post-seizure disorientation for 1-2 hours is normal`,
    `Mild sedation from anti-seizure meds is expected initially`,
    `Improvement from IVDD can be slow - weeks to months`,
    `Some wobbliness during recovery is normal`,
    `Increased appetite may occur with some neurological medications (steroids)`,
  ],

  warningSignsToMonitor: [
    `More frequent or longer seizures`,
    `Cluster seizures (2+ seizures in 24 hours)`,
    `Seizures lasting longer than 2-3 minutes`,
    `Difficulty breathing after seizures`,
    `Progressive weakness in limbs`,
    `Loss of bladder or bowel control`,
    `Unable to stand or walk`,
    `Not recognizing family members`,
    `Inability to eat or drink`,
    `Rolling and unable to right themselves`,
  ],

  emergencyCriteria: [
    `Seizure lasting more than 5 minutes (status epilepticus)`,
    `Multiple seizures within one hour (cluster seizures)`,
    `Complete paralysis with loss of pain sensation in limbs`,
    `Inability to breathe normally`,
    `Coma or complete unresponsiveness`,
    `Sudden collapse with inability to stand`,
    `Seizures with blue gums or difficulty breathing`,
  ],

  urgentCriteria: [
    `First-time seizure`,
    `Seizures becoming more frequent despite medication`,
    `Progressive weakness in legs over 24-48 hours`,
    `New onset of head tilt with inability to stand`,
    `Loss of bladder or bowel control`,
    `Not eating or drinking for 24+ hours`,
    `Severe disorientation or altered mentation`,
    `Dragging of limbs or knuckling of paws`,
  ],

  typicalRecoveryDays: 14,

  commonMedications: [
    'phenobarbital',
    'keppra',
    'levetiracetam',
    'zonisamide',
    'potassium bromide',
    'gabapentin',
    'prednisone',
    'prednisolone',
    'methocarbamol',
    'meclizine',
    'cerenia',
  ],
};
