/**
 * Respiratory Condition Knowledge Base
 *
 * Comprehensive knowledge base for respiratory conditions including kennel cough,
 * pneumonia, bronchitis, upper respiratory infections, and breathing difficulties.
 */

import type { ConditionKnowledgeBase } from '../types';

export const respiratoryKnowledge: ConditionKnowledgeBase = {
  conditionCategory: 'respiratory',
  displayName: 'Respiratory Issues',
  description:
    'Conditions affecting the respiratory system including kennel cough, pneumonia, bronchitis, upper respiratory infections, and asthma',

  keywords: [
    'cough',
    'coughing',
    'sneeze',
    'sneezing',
    'respiratory',
    'breathing',
    'wheeze',
    'wheezing',
    'pneumonia',
    'bronchitis',
    'kennel cough',
    'bordetella',
    'nasal discharge',
    'runny nose',
    'congestion',
    'upper respiratory',
    'uri',
    'asthma',
  ],

  assessmentQuestions: [
    {
      question: `Has the coughing improved since starting the medication?`,
      context: 'Primary indicator of treatment effectiveness',
      expectedPositiveResponse: [
        'much better',
        'coughing less',
        'almost stopped',
        'way better',
        'barely coughing',
        'significantly improved',
      ],
      concerningResponses: [
        'worse',
        'coughing more',
        'no improvement',
        'constant coughing',
        'coughing up blood',
        'can\'t stop coughing',
      ],
      followUpIfConcerning: `Is {{petName}} coughing so much that {{petName}} can't rest or sleep? And have you seen any blood in the cough?`,
      priority: 1,
      required: true,
    },
    {
      question: `How's {{petName}}'s energy level and activity compared to before?`,
      context: 'Energy level indicates respiratory function and oxygenation',
      expectedPositiveResponse: [
        'more energetic',
        'back to normal',
        'playing again',
        'active',
        'much better',
      ],
      concerningResponses: [
        'very lethargic',
        'won\'t move',
        'just lying around',
        'no energy',
        'worse',
        'labored breathing',
      ],
      followUpIfConcerning: `Is {{petName}} having any difficulty breathing, or do you notice {{petName}} breathing faster than normal even at rest?`,
      priority: 1,
      required: true,
    },
    {
      question: `Have you noticed any discharge from the nose or eyes?`,
      context: 'Discharge assessment for infection severity',
      expectedPositiveResponse: [
        'no discharge',
        'clearing up',
        'much better',
        'almost gone',
        'clear discharge only',
      ],
      concerningResponses: [
        'thick green discharge',
        'yellow discharge',
        'bloody discharge',
        'getting worse',
        'very thick',
      ],
      followUpIfConcerning: `What color is the discharge - clear, yellow, green, or bloody? Thick colored discharge can indicate a more serious infection.`,
      priority: 2,
      required: true,
    },
    {
      question: `Is {{petName}} eating and drinking normally?`,
      context: 'Appetite and hydration assessment',
      expectedPositiveResponse: [
        'eating well',
        'good appetite',
        'drinking normally',
        'back to normal',
      ],
      concerningResponses: [
        'not eating',
        'refusing food',
        'not drinking',
        'only eating tiny amounts',
      ],
      followUpIfConcerning: `Has {{petName}} refused food or water for more than 12 hours? This can lead to dehydration quickly.`,
      priority: 2,
      required: true,
    },
    {
      question: `Have you noticed any changes in {{petName}}'s breathing pattern - is it faster, harder, or different than normal?`,
      context: 'Critical assessment of respiratory distress',
      expectedPositiveResponse: [
        'breathing normally',
        'no changes',
        'breathing easier',
        'normal rate',
      ],
      concerningResponses: [
        'breathing fast',
        'open mouth breathing',
        'labored breathing',
        'struggling to breathe',
        'gasping',
        'blue gums',
      ],
      followUpIfConcerning: `Is {{petName}} breathing with mouth open, or do you see the chest and belly moving a lot with each breath? Are the gums pink or do they look pale or blue?`,
      priority: 1,
      required: true,
    },
    {
      question: `Is the cough productive - meaning is {{petName}} bringing up any mucus or phlegm?`,
      context: 'Helps differentiate dry cough from productive cough',
      expectedPositiveResponse: [
        'dry cough',
        'no mucus',
        'just a dry cough',
      ],
      concerningResponses: [
        'bringing up mucus',
        'phlegm',
        'gagging up stuff',
        'yellow mucus',
        'blood',
      ],
      followUpIfConcerning: `What does the mucus look like - is it clear, white, yellow, green, or does it have any blood in it?`,
      priority: 2,
      required: false,
    },
    {
      question: `Have you been able to keep {{petName}} calm and rested as we discussed?`,
      context: 'Rest is critical for respiratory recovery',
      expectedPositiveResponse: [
        'yes',
        'resting',
        'calm',
        'keeping quiet',
      ],
      concerningResponses: [
        'very active',
        'running around',
        'can\'t keep calm',
        'playing hard',
      ],
      followUpIfConcerning: `It's really important to limit activity during recovery to let the respiratory system heal. Can you try to keep {{petName}} more restricted?`,
      priority: 3,
      required: false,
    },
  ],

  normalPostTreatmentExpectations: [
    `Mild coughing may persist for 1-2 weeks even with treatment`,
    `Some nasal discharge during recovery is normal as the body clears infection`,
    `Energy levels may take 3-5 days to return to normal`,
    `Occasional reverse sneezing during recovery can occur`,
    `Some dogs may have reduced appetite for 24-48 hours`,
    `Kennel cough can take 10-14 days to fully resolve`,
    `Mild exercise intolerance during recovery is expected`,
  ],

  warningSignsToMonitor: [
    `Increased respiratory rate at rest (more than 30-40 breaths per minute)`,
    `Labored breathing or increased effort to breathe`,
    `Blue or pale gums`,
    `Coughing that prevents sleep or rest`,
    `Thick yellow or green nasal discharge`,
    `Bloody nasal discharge`,
    `Open mouth breathing at rest`,
    `Loss of appetite for more than 24 hours`,
    `Fever (panting, warm to touch)`,
    `No improvement after 3-5 days of treatment`,
  ],

  emergencyCriteria: [
    `Severe difficulty breathing or gasping for air`,
    `Blue or white gums`,
    `Collapse or extreme weakness`,
    `Open mouth breathing with distress`,
    `Coughing up blood`,
    `Inability to lie down due to breathing difficulty`,
    `Respiratory rate over 60 breaths per minute at rest`,
    `Choking or complete airway obstruction`,
  ],

  urgentCriteria: [
    `Labored breathing that's worsening`,
    `Persistent cough preventing sleep`,
    `Not eating or drinking for 24+ hours`,
    `Thick, discolored nasal discharge worsening`,
    `High fever with lethargy`,
    `No improvement or worsening after 5 days of treatment`,
    `Coughing fits that cause gagging or vomiting`,
    `Pale gums (not blue, but not normal pink)`,
  ],

  typicalRecoveryDays: 7,

  commonMedications: [
    'doxycycline',
    'azithromycin',
    'clavamox',
    'amoxicillin',
    'cephalexin',
    'hydrocodone',
    'butorphanol',
    'guaifenesin',
    'nebulization',
    'albuterol',
    'terbutaline',
  ],
};
