/**
 * Dermatological Condition Knowledge Base
 *
 * Comprehensive knowledge base for skin conditions including allergies, hot spots,
 * pyoderma, dermatitis, mange, and other skin/coat issues.
 */

import type { ConditionKnowledgeBase } from "../types";

export const dermatologicalKnowledge: ConditionKnowledgeBase = {
  conditionCategory: "dermatological",
  displayName: "Dermatological/Skin Issues",
  description:
    "Conditions affecting the skin and coat including allergies, hot spots, infections, dermatitis, and parasitic skin diseases",

  keywords: [
    "skin",
    "rash",
    "itch",
    "itchy",
    "scratching",
    "hot spot",
    "derma",
    "dermatitis",
    "pyoderma",
    "allergy",
    "allergic",
    "hives",
    "mange",
    "scabies",
    "flea",
    "tick",
    "hair loss",
    "bald",
    "red skin",
    "scabs",
    "crusts",
  ],

  assessmentQuestions: [
    {
      question: `Has the itching and scratching improved since starting treatment?`,
      context:
        "Primary indicator of treatment effectiveness for skin conditions",
      expectedPositiveResponse: [
        "much less itching",
        "barely scratching",
        "stopped scratching",
        "way better",
        "significantly improved",
        "almost stopped",
        "only occasional",
      ],
      concerningResponses: [
        "still scratching constantly",
        "worse",
        "no improvement",
        "scratching all the time",
        "keeping us up at night",
        "scratching until bleeding",
      ],
      followUpIfConcerning: `Is {{petName}} scratching so much that the skin is getting raw or bleeding? And are there any new areas that have become affected?`,
      priority: 1,
      required: true,
    },
    {
      question: `How does the affected skin area look now compared to when we first saw {{petName}}?`,
      context: "Visual assessment of skin healing progress",
      expectedPositiveResponse: [
        "looking better",
        "less red",
        "healing",
        "hair growing back",
        "drying up",
        "clearing up",
        "much improved",
      ],
      concerningResponses: [
        "worse",
        "more red",
        "spreading",
        "oozing",
        "bleeding",
        "new spots appearing",
        "getting bigger",
        "smells bad",
      ],
      followUpIfConcerning: `Is the area oozing or do you notice a bad odor? And has it spread to new areas of the body?`,
      priority: 1,
      required: true,
    },
    {
      question: `Is {{petName}} tolerating the medication okay? Any vomiting or diarrhea?`,
      context: "Many skin medications can cause GI upset",
      expectedPositiveResponse: [
        "tolerating well",
        "no problems",
        "taking it fine",
        "no side effects",
        "eating normally",
      ],
      concerningResponses: [
        "vomiting",
        "diarrhea",
        "not eating",
        "seems nauseous",
        "lethargic",
        "throwing up",
      ],
      followUpIfConcerning: `How many times has {{petName}} vomited since starting the medication? We may need to adjust the dosing.`,
      priority: 2,
      required: true,
    },
    {
      question: `Have you been giving the medication with food as directed?`,
      context: "Many dermatological medications need to be given with food",
      expectedPositiveResponse: [
        "yes",
        "with meals",
        "always with food",
        "following directions",
      ],
      concerningResponses: [
        "on empty stomach",
        "forgot",
        "not always",
        "sometimes",
      ],
      followUpIfConcerning: `It's important to give this medication with food to prevent stomach upset. Can you make sure to do that going forward?`,
      priority: 3,
      required: false,
    },
    {
      question: `If we prescribed medicated baths or topical treatments, have you been able to do those?`,
      context: "Compliance with topical treatments is critical",
      expectedPositiveResponse: [
        "yes",
        "doing them",
        "bathing as directed",
        "applying as instructed",
        "twice a week",
      ],
      concerningResponses: [
        "having trouble",
        "not yet",
        "too difficult",
        "pet won't let me",
        "haven't started",
      ],
      followUpIfConcerning: `I understand bathing can be challenging. Would it help if we showed you some techniques, or would you like to bring {{petName}} in for us to do the baths?`,
      priority: 2,
      required: false,
    },
    {
      question: `Are you still seeing any hair loss or new bald patches developing?`,
      context:
        "Hair loss assessment for conditions like mange or severe allergies",
      expectedPositiveResponse: [
        "no new hair loss",
        "hair growing back",
        "no new bald spots",
        "improving",
      ],
      concerningResponses: [
        "more hair loss",
        "new bald patches",
        "spreading",
        "getting worse",
      ],
      followUpIfConcerning: `Where are the new bald patches appearing? Are they in the same areas or different locations?`,
      priority: 2,
      required: false,
    },
    {
      question: `Have you noticed {{petName}} licking or chewing at the paws specifically?`,
      context: "Paw licking often indicates allergies or anxiety",
      expectedPositiveResponse: ["no", "not anymore", "stopped", "much less"],
      concerningResponses: [
        "constantly",
        "all the time",
        "obsessively",
        "paws are red",
        "staining the fur",
      ],
      followUpIfConcerning: `Are the paws red, swollen, or have a yeasty odor? This might need additional treatment.`,
      priority: 3,
      required: false,
    },
  ],

  normalPostTreatmentExpectations: [
    `Itching may take 3-7 days to significantly improve even with treatment`,
    `Some mild itching during healing is normal as skin repairs itself`,
    `Hair regrowth can take several weeks even after skin has healed`,
    `Skin may appear flaky or scaly during healing process`,
    `Some redness may persist for a few days even with improvement`,
    `Antihistamines may cause drowsiness - this is normal and expected`,
    `Steroids may cause increased thirst and urination - this is a known side effect`,
  ],

  warningSignsToMonitor: [
    `Scratching that causes bleeding or open wounds`,
    `Spreading of rash or skin lesions to new areas`,
    `Development of foul odor from the skin`,
    `Oozing, weeping, or discharge from affected areas`,
    `Skin becoming very hot to the touch`,
    `Swelling of face, muzzle, or around eyes (potential allergic reaction)`,
    `Difficulty breathing or excessive panting (rare but serious allergic reaction)`,
    `Signs of pain when touching affected areas`,
    `No improvement after 5-7 days of treatment`,
  ],

  emergencyCriteria: [
    `Sudden facial swelling, especially around eyes or muzzle (angioedema)`,
    `Difficulty breathing, wheezing, or blue gums (anaphylaxis)`,
    `Hives appearing rapidly all over the body with distress`,
    `Large areas of skin peeling or sloughing off`,
    `Severe skin infections with fever and lethargy`,
    `Inability to walk due to swollen, painful paws`,
  ],

  urgentCriteria: [
    `No improvement after 7 days of treatment`,
    `Skin condition worsening despite treatment`,
    `Development of secondary infection (oozing, foul smell, green/yellow discharge)`,
    `Excessive scratching causing multiple bleeding wounds`,
    `Severe lethargy or refusing to eat (may indicate medication reaction)`,
    `Persistent vomiting or diarrhea from medication`,
    `New bald patches developing rapidly`,
    `Signs of pain or crying when touched`,
  ],

  typicalRecoveryDays: 7,

  commonMedications: [
    "apoquel",
    "cytopoint",
    "prednisone",
    "prednisolone",
    "benadryl",
    "diphenhydramine",
    "hydroxyzine",
    "cephalexin",
    "clavamox",
    "ketoconazole",
    "fluconazole",
    "malaseb shampoo",
    "chlorhexidine",
    "medicated shampoo",
  ],
};
