/**
 * Orthopedic Condition Knowledge Base
 *
 * Comprehensive knowledge base for musculoskeletal conditions including arthritis,
 * limping, cruciate tears, hip dysplasia, and mobility issues.
 */

import type { ConditionKnowledgeBase } from "../types";

export const orthopedicKnowledge: ConditionKnowledgeBase = {
  conditionCategory: "orthopedic",
  displayName: "Orthopedic/Musculoskeletal Issues",
  description:
    "Conditions affecting bones, joints, muscles, and mobility including arthritis, limping, cruciate tears, hip dysplasia, and fractures",

  keywords: [
    "limp",
    "limping",
    "lame",
    "lameness",
    "arthritis",
    "orthopedic",
    "joint",
    "bone",
    "fracture",
    "hip",
    "knee",
    "elbow",
    "cruciate",
    "acl",
    "ccl",
    "mobility",
    "leg",
    "paw",
    "shoulder",
    "back",
    "spine",
    "dysplasia",
  ],

  assessmentQuestions: [
    {
      question: `Has the limping improved since starting the pain medication?`,
      context: "Primary indicator of pain control and joint improvement",
      expectedPositiveResponse: [
        "much better",
        "barely limping",
        "walking normally",
        "way better",
        "using the leg more",
        "improved",
      ],
      concerningResponses: [
        "still limping badly",
        "worse",
        "won't use the leg",
        "holding it up",
        "no improvement",
        "three-legged",
      ],
      followUpIfConcerning: `Is {{petName}} able to put any weight on the leg at all, or is {{petName}} completely avoiding using it?`,
      priority: 1,
      required: true,
    },
    {
      question: `How's {{petName}} doing with getting up from lying down? Is that easier than before?`,
      context: "Mobility assessment, especially important for arthritis",
      expectedPositiveResponse: [
        "getting up easier",
        "not struggling as much",
        "much better",
        "jumping up fine",
      ],
      concerningResponses: [
        "really struggling",
        "can't get up",
        "yelps when standing",
        "takes several tries",
        "worse",
      ],
      followUpIfConcerning: `Does {{petName}} cry or yelp when trying to stand? And about how long does it take {{petName}} to get up?`,
      priority: 1,
      required: true,
    },
    {
      question: `Is {{petName}} more willing to go for walks or play, or still reluctant?`,
      context: "Activity level indicates pain control and joint function",
      expectedPositiveResponse: [
        "more active",
        "wants to play",
        "enjoying walks",
        "back to normal energy",
        "running around",
      ],
      concerningResponses: [
        "won't walk",
        "refuses to go out",
        "stops after a few steps",
        "no interest in play",
        "same as before",
      ],
      followUpIfConcerning: `How far can {{petName}} walk before showing signs of discomfort or wanting to stop?`,
      priority: 2,
      required: true,
    },
    {
      question: `Have you noticed any swelling or heat in the affected joint or leg?`,
      context: "Inflammation assessment",
      expectedPositiveResponse: [
        "no swelling",
        "looks normal",
        "not hot",
        "swelling went down",
      ],
      concerningResponses: [
        "very swollen",
        "hot to touch",
        "getting bigger",
        "painful when touched",
      ],
      followUpIfConcerning: `Is the swelling getting worse? And does {{petName}} pull away or cry when you touch that area?`,
      priority: 2,
      required: false,
    },
    {
      question: `Are you giving the medication with food as directed?`,
      context: "NSAIDs must be given with food to prevent stomach upset",
      expectedPositiveResponse: [
        "yes",
        "always with food",
        "with meals",
        "following directions",
      ],
      concerningResponses: ["on empty stomach", "sometimes", "forgot"],
      followUpIfConcerning: `It's very important to give this medication with food to protect the stomach. Can you make sure to do that from now on?`,
      priority: 2,
      required: false,
    },
    {
      question: `Have you noticed any vomiting, diarrhea, or loss of appetite since starting the pain medication?`,
      context: "NSAID side effects monitoring - very important",
      expectedPositiveResponse: [
        "no",
        "eating normally",
        "no problems",
        "tolerating well",
      ],
      concerningResponses: [
        "vomiting",
        "diarrhea",
        "not eating",
        "black stool",
        "bloody stool",
      ],
      followUpIfConcerning: `This could be a side effect of the medication. Has the stool been black or tar-like? We may need to stop the medication and switch to something else.`,
      priority: 1,
      required: false,
    },
    {
      question: `Have you been able to keep {{petName}}'s activity restricted as we discussed?`,
      context: "Rest is critical for healing orthopedic injuries",
      expectedPositiveResponse: [
        "yes",
        "keeping calm",
        "restricted",
        "short walks only",
      ],
      concerningResponses: [
        "very active",
        "running around",
        "can't keep calm",
        "jumping",
      ],
      followUpIfConcerning: `Activity restriction is really important for healing. Is there a way we can help you keep {{petName}} more confined - maybe a crate or small room?`,
      priority: 3,
      required: false,
    },
  ],

  normalPostTreatmentExpectations: [
    `Some stiffness, especially after rest, may persist for weeks`,
    `Gradual improvement over 5-7 days is typical`,
    `Cool weather may worsen arthritis symptoms temporarily`,
    `Some limping after exercise is normal during recovery`,
    `NSAIDs may cause increased thirst - this is expected`,
    `Full recovery from soft tissue injuries can take 4-6 weeks`,
    `Arthritis is managed, not cured - ongoing treatment may be needed`,
  ],

  warningSignsToMonitor: [
    `Sudden worsening of limping or unable to bear weight`,
    `Swelling that's increasing`,
    `Crying or yelping when touched`,
    `Black, tarry stools (NSAID side effect)`,
    `Vomiting (especially if coffee-ground appearance)`,
    `Loss of appetite for more than 24 hours`,
    `Knuckling of paws or dragging toes`,
    `Complete refusal to use the limb`,
    `No improvement after 5-7 days`,
  ],

  emergencyCriteria: [
    `Complete inability to stand or walk`,
    `Dragging rear legs with loss of bladder/bowel control (possible disc disease)`,
    `Severe pain with crying/screaming when touched`,
    `Vomiting blood or coffee-ground material (NSAID emergency)`,
    `Black, tarry stools with weakness (GI bleeding from NSAIDs)`,
    `Obvious fracture or bone protruding`,
    `Joint dislocation with severe deformity`,
  ],

  urgentCriteria: [
    `Limping that's significantly worse despite medication`,
    `New limping in a different leg`,
    `Inability to get up even with assistance`,
    `Persistent vomiting or diarrhea on NSAIDs`,
    `Loss of appetite for more than 24 hours while on medication`,
    `Swelling that's rapidly increasing`,
    `Signs of severe pain that medication isn't controlling`,
    `No improvement after 7 days of treatment`,
  ],

  typicalRecoveryDays: 14,

  commonMedications: [
    "carprofen",
    "rimadyl",
    "meloxicam",
    "galliprant",
    "onsior",
    "deramaxx",
    "gabapentin",
    "tramadol",
    "adequan",
    "dasuquin",
    "cosequin",
    "glucosamine",
    "fish oil",
    "omega-3",
  ],
};
